# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Run FLASK

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:  
    - uses: actions/checkout@v4
    - name: Set up python 3.9 
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
 
    - name: Install Python dependencies
      run: |
        sudo apt install python3-pip -y
        pip install pandas
        pip install numpy
        pip install flask
        pip install torch --no-cache-dir
        pip install scikit-learn --no-cache-dir
        pip install sentence-transformers --no-cache-dir
        
  deploy:
    # needs를 통해 build job이 수행 성공시에 작업되도록 설정
    needs: build
    runs-on: ubuntu-latest

    steps:
    ## deploy to production
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
        username: root
        password: ${{ secrets.HOST_PWD }} #id_ed25519
        port: 22
        envs: GITHUB_SHA
        script: |
          python3 ./CICD_teset/main__.py
