# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Run FLASK

on: [pull]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:  
    - uses: actions/checkout@v4
    - name: Set up python 3.9 
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create virtual environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
        username: root
        password: ${{ secrets.HOST_PWD }} #id_ed25519
        port: 22
        envs: GITHUB_SHA

        script: |
          python3 -m venv venv
          source venv/bin/activate   
          sudo apt install python3-pip -y
          pip install pandas
          pip install numpy
          pip install flask
          pip install torch --no-cache-dir
          pip install scikit-learn --no-cache-dir
          pip install sentence-transformers --no-cache-dir
          cd CICD_test
          cd python
          python3 main__.py
